parameters:
    tables.eru.nczone.players: %core.table_prefix%zone_players
    tables.eru.nczone.civs: %core.table_prefix%zone_civs
    tables.eru.nczone.maps: %core.table_prefix%zone_maps
    tables.eru.nczone.map_civs: %core.table_prefix%zone_map_civs
    tables.eru.nczone.matches: %core.table_prefix%zone_matches
    tables.eru.nczone.match_teams: %core.table_prefix%zone_match_teams
    tables.eru.nczone.match_players: %core.table_prefix%zone_match_players
    tables.eru.nczone.match_civs: %core.table_prefix%zone_match_civs
    tables.eru.nczone.match_team_civs: %core.table_prefix%zone_match_team_civs
    tables.eru.nczone.match_player_civs: %core.table_prefix%zone_match_player_civs
    tables.eru.nczone.player_map: %core.table_prefix%zone_player_map
    tables.eru.nczone.player_civ: %core.table_prefix%zone_player_civ
    tables.eru.nczone.bets: %core.table_prefix%zone_bets
    tables.eru.nczone.draw_process: %core.table_prefix%zone_draw_process
    tables.eru.nczone.draw_players: %core.table_prefix%zone_draw_players
