eru_nczone_controller_rmatches:
    path: /nczone/rmatches
    defaults: { _controller: eru.nczone.controller:rmatches }

eru_nczone_controller_pmatches:
    path: /nczone/pmatches
    defaults: { _controller: eru.nczone.controller:pmatches }

eru_nczone_controller_table:
    path: /nczone/table
    defaults: { _controller: eru.nczone.controller:table }

eru_nczone_controller__api__logged_in_players:
    path: /nczone/api/players/logged_in
    defaults: { _controller: eru.nczone.controller.api:logged_in_players }

eru_nczone_controller__api__all_players:
    path: /nczone/api/players
    defaults: { _controller: eru.nczone.controller.api:all_players }

eru_nczone_controller__api__running_matches:
    path: /nczone/api/rmatches
    defaults: { _controller: eru.nczone.controller.api:rmatches }

eru_nczone_controller__api__past_matches:
    path: /nczone/api/pmatches
    defaults: { _controller: eru.nczone.controller.api:pmatches }

eru_nczone_controller__api__me:
    path: /nczone/api/me
    defaults: { _controller: eru.nczone.controller.api:me }

eru_nczone_controller__api__me_login:
    path: /nczone/api/me/login
    defaults: { _controller: eru.nczone.controller.api:me_login }

eru_nczone_controller__api__me_logout:
    path: /nczone/api/me/logout
    defaults: { _controller: eru.nczone.controller.api:me_logout }

eru_nczone_controller__api__draw_preview:
    path: /nczone/api/draw/preview
    defaults: { _controller: eru.nczone.controller.api:draw_preview }

eru_nczone_controller__api__draw_cancel:
    path: /nczone/api/draw/cancel
    defaults: { _controller: eru.nczone.controller.api:draw_cancel }

eru_nczone_controller__api__draw_confirm:
    path: /nczone/api/draw/confirm
    defaults: { _controller: eru.nczone.controller.api:draw_confirm }

eru_nczone_controller__api__information:
    path: /nczone/api/information
    defaults: { _controller: eru.nczone.controller.api:information }
